# Generated by Django 3.1.5 on 2021-02-03 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_name', models.CharField(blank=True, db_index=True, default='', max_length=2048, verbose_name='Official Name')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_government', to='regions.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Local Government',
                'verbose_name_plural': 'Local Government Units',
                'ordering': ('created_at',),
            },
        ),
    ]
